name: .NET Test

on:
  push:
    branches: [ main, master ]
    paths:
      - 'dotnet/**'
      - '.github/workflows/dotnet-test.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'dotnet/**'
      - '.github/workflows/dotnet-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      working-directory: dotnet
      run: dotnet restore

    - name: Build
      working-directory: dotnet
      run: dotnet build --no-restore --configuration Release

    - name: Test
      working-directory: dotnet
      run: dotnet test --no-build --configuration Release --verbosity normal
