#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Updates part repositories with xRegistry links.

.DESCRIPTION
    This script updates each part repository's README.md and specs.json
    to include links to the xRegistry catalog.

.PARAMETER PartRepoPath
    Path to a specific part repository to update (optional - if not provided, prompts for each part)

.PARAMETER RegistryUrl
    Base URL for the registry (default: https://spec-works.github.io/registry)

.EXAMPLE
    .\update-parts-with-registry.ps1
    
.EXAMPLE
    .\update-parts-with-registry.ps1 -PartRepoPath C:\src\github\spec-works\vCard

.NOTES
    Generated by: GitHub Copilot CLI
    Part of: SpecWorks Factory tooling (Issue #6 Phase 5)
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$PartRepoPath = "",
    
    [Parameter()]
    [string]$RegistryUrl = "https://spec-works.github.io/registry"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "🔗 SpecWorks Part Registry Integration" -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host ""

# Function to update specs.json with registry link
function Add-RegistryLinkToSpecs {
    param(
        [string]$SpecsPath,
        [string]$PartId,
        [string]$RegistryUrl
    )
    
    if (-not (Test-Path $SpecsPath)) {
        Write-Warning "specs.json not found at: $SpecsPath"
        return $false
    }
    
    $specs = Get-Content $SpecsPath -Raw | ConvertFrom-Json
    
    # Check if registry link already exists
    $registryLink = $specs.linkset | Where-Object { $_.rel -eq "registry" }
    
    if ($registryLink) {
        Write-Host "   ✓ Registry link already exists" -ForegroundColor Yellow
        return $false
    }
    
    # Add registry link
    $newLink = @{
        href = "$RegistryUrl/parts/$PartId/"
        rel = "registry"
        title = "Part registry entry"
    }
    
    $specs.linkset += $newLink
    
    # Save updated specs.json
    $specs | ConvertTo-Json -Depth 10 | Set-Content -Path $SpecsPath
    
    Write-Host "   ✓ Added registry link to specs.json" -ForegroundColor Green
    return $true
}

# Function to add registry badge to README
function Add-RegistryBadgeToReadme {
    param(
        [string]$ReadmePath,
        [string]$PartId,
        [string]$PartName,
        [string]$RegistryUrl
    )
    
    if (-not (Test-Path $ReadmePath)) {
        Write-Warning "README.md not found at: $ReadmePath"
        return $false
    }
    
    $readme = Get-Content $ReadmePath -Raw
    
    # Check if registry badge already exists
    if ($readme -match "spec-works\.github\.io/registry") {
        Write-Host "   ✓ Registry link already in README" -ForegroundColor Yellow
        return $false
    }
    
    # Find the title line
    if ($readme -match "(?m)^# (.+)$") {
        $title = $matches[1]
        
        # Create registry badge
        $registryBadge = "[![Registry](https://img.shields.io/badge/Registry-SpecWorks-blue)]($RegistryUrl/parts/$PartId/)"
        
        # Try to insert after existing badges or after title
        if ($readme -match "(?m)^(# .+\r?\n)((?:\[!\[.+?\]\(.+?\)\]\(.+?\)\s*)+)") {
            # Insert alongside existing badges
            $readme = $readme -replace "(?m)^(# .+\r?\n)((?:\[!\[.+?\]\(.+?\)\]\(.+?\)\s*)+)", "`$1`$2$registryBadge`n"
        }
        elseif ($readme -match "(?m)^# .+\r?\n\r?\n") {
            # Insert after title with blank line
            $readme = $readme -replace "(?m)^(# .+\r?\n)", "`$1$registryBadge`n`n"
        }
        else {
            # Insert right after title
            $readme = $readme -replace "(?m)^(# .+)$", "`$1`n$registryBadge"
        }
        
        Set-Content -Path $ReadmePath -Value $readme -NoNewline
        Write-Host "   ✓ Added registry badge to README.md" -ForegroundColor Green
        return $true
    }
    
    return $false
}

# Process single part or prompt for each
if ($PartRepoPath) {
    $parts = @(@{
        Path = $PartRepoPath
        Name = Split-Path $PartRepoPath -Leaf
        Id = (Split-Path $PartRepoPath -Leaf).ToLower()
    })
}
else {
    # Find all part repos
    $sourceRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
    $excludedDirs = @('.claude', '.github', 'spec-works.github.io', 'specification')
    
    $partDirs = Get-ChildItem -Path $sourceRoot -Directory | 
        Where-Object { $excludedDirs -notcontains $_.Name } |
        Where-Object { Test-Path (Join-Path $_.FullName "specs.json") }
    
    $parts = $partDirs | ForEach-Object {
        @{
            Path = $_.FullName
            Name = $_.Name
            Id = $_.Name.ToLower()
        }
    }
}

Write-Host "📦 Found $($parts.Count) parts to update:" -ForegroundColor Green
$parts | ForEach-Object { Write-Host "   - $($_.Name)" }
Write-Host ""

# Update each part
$updatedCount = 0
foreach ($part in $parts) {
    Write-Host "🔧 Processing: $($part.Name)" -ForegroundColor Yellow
    
    $specsPath = Join-Path $part.Path "specs.json"
    $readmePath = Join-Path $part.Path "README.md"
    
    $specsUpdated = Add-RegistryLinkToSpecs -SpecsPath $specsPath -PartId $part.Id -RegistryUrl $RegistryUrl
    $readmeUpdated = Add-RegistryBadgeToReadme -ReadmePath $readmePath -PartId $part.Id -PartName $part.Name -RegistryUrl $RegistryUrl
    
    if ($specsUpdated -or $readmeUpdated) {
        $updatedCount++
        Write-Host ""
    }
    else {
        Write-Host "   → No changes needed" -ForegroundColor Gray
        Write-Host ""
    }
}

# Summary
Write-Host "✅ Update complete!" -ForegroundColor Green
Write-Host ""
Write-Host "📊 Summary:" -ForegroundColor Cyan
Write-Host "   Parts processed: $($parts.Count)"
Write-Host "   Parts updated:   $updatedCount"
Write-Host ""

if ($updatedCount -gt 0) {
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "1. Review changes in each part repository"
    Write-Host "2. Create PRs for updated parts:"
    Write-Host "   cd <part-repo>"
    Write-Host "   git checkout -b add-registry-links"
    Write-Host "   git add README.md specs.json"
    Write-Host "   git commit -m 'Add xRegistry links'"
    Write-Host "   gh pr create --fill"
    Write-Host ""
}
else {
    Write-Host "All parts are already up to date!" -ForegroundColor Green
}
